---
- name: Check image registry if installed
  ignore_errors: true
  command: systemctl status harbor.service
  register: image_registry_service

- name: Sync harbor package to remote
  copy:
    src: "{{ work_dir }}/kubekey/image-registry/harbor/{{ harbor_version }}/{{ binary_type.stdout }}/harbor-offline-installer-{{ harbor_version }}.tgz"
    dest: "/opt/harbor/{{ harbor_version }}/harbor-offline-installer-{{ harbor_version }}.tgz"
  when: image_registry_service.stderr != ""

- name: Untar harbor package
  command: |
    cd /opt/harbor/{{ harbor_version }}/ && tar -zxvf harbor-offline-installer-{{ harbor_version }}.tgz
  when: image_registry_service.stderr != ""

- name: Sync image registry cert file to remote
  copy:
    src: "{{ work_dir }}/kubekey/pki/image_registry.crt"
    dest: "/opt/harbor/{{ harbor_version }}/ssl/server.crt"
  when: image_registry_service.stderr != ""

- name: Sync image registry key file to remote
  copy:
    src: "{{ work_dir }}/kubekey/pki/image_registry.key"
    dest: "/opt/harbor/{{ harbor_version }}/ssl/server.key"
  when: image_registry_service.stderr != ""

- name: Generate harbor config
  template:
    src: "harbor.config"
    dest: "/opt/harbor/{{ harbor_version }}/harbor/harbor.yml"
  when: image_registry_service.stderr != ""

- name: Generate keepalived docker compose
  template:
    src: "harbor_keepalived.docker-compose"
    dest: "/opt/harbor/{{ harbor_version }}/harbor/docker-compose-keepalived.yml"
  when:
    - image_registry.ha_vip | defined
    - image_registry_service.stderr != ""

- name: Install harbor
  command: |
    cd /opt/harbor/{{ harbor_version }}/harbor && /bin/bash install.sh
  when: image_registry_service.stderr != ""

- name: Register harbor service
  template:
    src: "harbor.service"
    dest: "/etc/systemd/system/harbor.service"
  when: image_registry_service.stderr != ""

- name: Start harbor service
  command: systemctl daemon-reload && systemctl start harbor.service && systemctl enable harbor.service
  when: image_registry_service.stderr != ""
