---
- name: Sync cilium helm chart to remote
  copy:
    src: "{{ work_dir }}/kubekey/cni/cilium-{{ cilium_version }}.tgz"
    dest: "/etc/kubernetes/cni/cilium-{{ cilium_version }}.tgz"

# https://docs.cilium.io/en/stable/installation/k8s-install-helm/
- name: Install cilium
  command: |
    helm install cilium /etc/kubernetes/cni/cilium-{{ cilium_version }}.tgz --namespace kube-system \
      --set operator.image.override={{ cni.cilium.operator_image }} \
      --set operator.replicas={{ cni.cilium.operator_replicas }} \
      --set image.override={{ cni.cilium.cilium_image }} \
      --set ipv6.enabled={% if (cni.ipv6_support=="true") %}true{%else%}false{% endif %} \
      --set ipv4NativeRoutingCIDR: {{ cni.kube_pods_v4_cidr }} \
    {% if (cni.ipv6_support=="true") %}
      --set ipv6NativeRoutingCIDR: {{ cni.kube_pods_v6_cidr }} \
    {% endif %}
    {% if (cni.kube_proxy=="true") %}
      --set kubeProxyReplacement=strict --set k8sServiceHost={{ cni.cilium.k8s_endpoint }} --set k8sServicePort={{ cni.cilium.k8s_port }}
    {% endif  %}
