---
- name: Check if runc is installed
  ignore_errors: true
  command: runc --version
  register: runc_install_version

- name: Sync runc binary to remote
  copy:
    src: "{{ work_dir }}/kubekey/runc/{{ runc_version }}/{{ binary_type.stdout }}/runc.{{ binary_type.stdout }}"
    dest: "/usr/local/bin/runc"
    mode: 0755
  when: runc_install_version.stderr != ""

- name: Check if containerd is installed
  ignore_errors: true
  command: containerd --version
  register: containerd_install_version

- name: Sync containerd binary to remote
  copy:
    src: "{{ work_dir }}/kubekey/containerd/{{ containerd_version }}/{{ binary_type.stdout }}/containerd-{{ containerd_version|slice:'1:' }}-linux-{{ binary_type.stdout }}.tar.gz"
    dest: "/tmp/kubekey/containerd-{{ containerd_version|slice:'1:' }}-linux-{{ binary_type.stdout }}.tar.gz"
  when: containerd_install_version.stderr != ""

- name: Unpackage containerd binary
  command: |
    tar -xvf /tmp/kubekey/containerd-{{ containerd_version|slice:'1:' }}-linux-{{ binary_type.stdout }}.tar.gz -C /usr/local/bin/
  when: containerd_install_version.stderr != ""

- name: Generate containerd config file
  template:
    src: containerd.config
    dest: /etc/containerd/config.toml
  when: containerd_install_version.stderr != ""

- name: Generate containerd Service file
  copy:
    src: containerd.service
    dest: /etc/systemd/system/containerd.service
  when: containerd_install_version.stderr != ""

- name: Start containerd
  command: |
    systemctl daemon-reload && systemctl start containerd.service && systemctl enable containerd.service
  when: containerd_install_version.stderr != ""
