---
- hosts:
    - k8s_cluster
    - etcd
  gather_facts: true
  roles:
    - precheck/env_check

- hosts:
    - localhost
  roles:
    - role: precheck/artifact_check
      when: artifact_file | defined
