---
- name: Stop if unsupported version of Kubernetes
  assert:
    that: kube_version | version:'>={{ cluster_require.kube_version_min_required }}'
    fail_msg: "The current release of Kubespray only support newer version of Kubernetes than {{ kube_version_min_required }} - You are trying to apply {{ kube_version }}"
  when:
    - kube_version | defined

- include_tasks: etcd.yaml

- include_tasks: os.yaml

- include_tasks: network.yaml

- include_tasks: cri.yaml

- include_tasks: nfs.yaml
