- hosts:
    - localhost
  tags: ["certs"]
  roles:
    - init/init-artifact

- hosts:
    - etcd
  tags: ["certs"]
  roles:
    - role: certs/renew-etcd
      when: groups['etcd']|length > 0 && renew_etcd

- hosts:
    - image_registry
  tags: ["certs"]
  roles:
    - role: certs/renew-registry
      when: groups['image_registry']|length > 0 && renew_image_registry

- hosts:
    - kube_control_plane
  tags: ["certs"]
  roles:
    - role: certs/renew-kubernetes
      when: groups['kube_control_plane']|length > 0 && renew_kubernetes
