---
- hosts:
    - nfs
  gather_facts: true
  roles:
    - install/nfs

- hosts:
    - etcd
  gather_facts: true
  roles:
    - install/etcd

- hosts:
    - image_registry
  gather_facts: true
  roles:
    - install/image-registry

- hosts:
    - k8s_cluster
  gather_facts: true
  roles:
    - install/cri
    - install/kubernetes

- hosts:
    - kube_control_plane
  roles:
    - role: install/certs
      when: renew_certs.enabled|default_if_none:false

- hosts:
    - k8s_cluster|random
  roles:
    - addons/cni
    - addons/kata
    - addons/nfd
    - addons/sc
