apiVersion: kubekey.kubesphere.io/v1
kind: Inventory
metadata:
  name: example
spec:
  hosts: # your can set all nodes here. or set nodes on special groups.
    node1:
      ssh_host: xxxxx
      ssh_port: 22
      ssh_user: user
      ssh_password: password
    node2:
      ssh_host: xxxxx
      ssh_port: 22
      ssh_user: user
      ssh_password: password
    node3:
      ssh_host: xxxxx
      ssh_port: 22
      ssh_user: user
      ssh_password: password
  groups:
    # all kubernetes nodes.
    k8s_cluster:
      groups:
        - kube_control_plane
        - kube_node
    # control_plane nodes
    kube_control_plane:
      hosts:
        - node1
    # worker nodes
    kube_node:
      hosts:
        - node2
    # etcd nodes when etcd_deployment_type is external
    etcd:
      hosts:
        - node3
